// フォニックス辞書:単語を「文字のまとまり → 音」に分ける表
// 形式: 単語(小文字): [[つづりのまとまり, 音の名前], ...]
//   音の名前は下の PHONEME_IPA の見出し。ふたつの音が続くときは配列(例 one → ["w","ah","n"])。
//   ただし x のように間を空けず一息で読む音は、配列にせず1つの音(ks)として作ってある。
//   よまない文字(サイレントe など)は null にする。
// 音声ファイルは scripts/build-phonics.py が phonics/<音の名前>.m4a に作る。

// 画面に表示する発音記号(音の名前 → IPA)
const PHONEME_IPA = {
  p: "p", b: "b", t: "t", d: "d", k: "k", g: "ɡ", ch: "tʃ", j: "dʒ",
  f: "f", v: "v", th: "θ", dh: "ð", s: "s", z: "z", sh: "ʃ", h: "h",
  m: "m", n: "n", ng: "ŋ", l: "l", r: "r", w: "w", y: "j", ks: "ks", ts: "ts",
  ae: "æ", eh: "e", ih: "ɪ", iy: "iː", aa: "ɑ", ah: "ʌ", uh: "ə",
  uu: "ʊ", uw: "uː", er: "ɚ", el: "əl", ar: "ɑr", or: "ɔr",
  ay: "aɪ", ey: "eɪ", ow: "aʊ", oh: "oʊ", oy: "ɔɪ", aw: "ɔ"
};

// 母音の音(画面で赤っぽく表示する)
const VOWEL_SOUNDS = ["ae","eh","ih","iy","aa","ah","uh","uu","uw","er","el","ar","or","ay","ey","ow","oh","oy","aw"];

const PHONICS = {
  a: [["a","uh"]],
  and: [["a","ae"],["n","n"],["d","d"]],
  apple: [["a","ae"],["pp","p"],["le","el"]],
  away: [["a","uh"],["w","w"],["ay","ey"]],
  banana: [["b","b"],["a","uh"],["n","n"],["a","ae"],["n","n"],["a","uh"]],
  bird: [["b","b"],["ir","er"],["d","d"]],
  blue: [["b","b"],["l","l"],["ue","uw"]],
  cat: [["c","k"],["a","ae"],["t","t"]],
  colors: [["c","k"],["o","ah"],["l","l"],["or","er"],["s","z"]],
  comes: [["c","k"],["o","ah"],["m","m"],["e",null],["s","z"]],
  day: [["d","d"],["ay","ey"]],
  down: [["d","d"],["ow","ow"],["n","n"]],
  everyone: [["e","eh"],["v","v"],["er","r"],["y","iy"],["one",["w","ah","n"]]],
  fast: [["f","f"],["a","ae"],["s","s"],["t","t"]],
  fish: [["f","f"],["i","ih"],["sh","sh"]],
  flower: [["f","f"],["l","l"],["ow","ow"],["er","er"]],
  food: [["f","f"],["oo","uw"],["d","d"]],
  friend: [["f","f"],["r","r"],["ie","eh"],["n","n"],["d","d"]],
  frog: [["f","f"],["r","r"],["o","aa"],["g","g"]],
  fun: [["f","f"],["u","ah"],["n","n"]],
  garden: [["g","g"],["ar","ar"],["d","d"],["e","uh"],["n","n"]],
  gives: [["g","g"],["i","ih"],["v","v"],["e",null],["s","z"]],
  go: [["g","g"],["o","oh"]],
  good: [["g","g"],["oo","uu"],["d","d"]],
  green: [["g","g"],["r","r"],["ee","iy"],["n","n"]],
  happy: [["h","h"],["a","ae"],["pp","p"],["y","iy"]],
  home: [["h","h"],["o","oh"],["m","m"],["e",null]],
  hungry: [["h","h"],["u","ah"],["n","ng"],["g","g"],["r","r"],["y","iy"]],
  i: [["I","ay"]],
  in: [["i","ih"],["n","n"]],
  is: [["i","ih"],["s","z"]],
  it: [["i","ih"],["t","t"]],
  kitchen: [["k","k"],["i","ih"],["tch","ch"],["e","uh"],["n","n"]],
  lets: [["l","l"],["e","eh"],["t's","ts"]],
  little: [["l","l"],["i","ih"],["tt","t"],["le","el"]],
  look: [["l","l"],["oo","uu"],["k","k"]],
  looks: [["l","l"],["oo","uu"],["k","k"],["s","s"]],
  love: [["l","l"],["o","ah"],["v","v"],["e",null]],
  milk: [["m","m"],["i","ih"],["l","l"],["k","k"]],
  mom: [["m","m"],["o","aa"],["m","m"]],
  momo: [["m","m"],["o","oh"],["m","m"],["o","oh"]],
  morning: [["m","m"],["or","or"],["n","n"],["i","ih"],["ng","ng"]],
  my: [["m","m"],["y","ay"]],
  new: [["n","n"],["ew","uw"]],
  no: [["n","n"],["o","oh"]],
  oh: [["oh","oh"]],
  on: [["o","aa"],["n","n"]],
  one: [["one",["w","ah","n"]]],
  opens: [["o","oh"],["p","p"],["e","uh"],["n","n"],["s","z"]],
  park: [["p","p"],["ar","ar"],["k","k"]],
  pink: [["p","p"],["i","ih"],["n","ng"],["k","k"]],
  play: [["p","p"],["l","l"],["ay","ey"]],
  pond: [["p","p"],["o","aa"],["n","n"],["d","d"]],
  rain: [["r","r"],["ai","ey"],["n","n"]],
  red: [["r","r"],["e","eh"],["d","d"]],
  ride: [["r","r"],["i","ay"],["d","d"],["e",null]],
  run: [["r","r"],["u","ah"],["n","n"]],
  sandbox: [["s","s"],["a","ae"],["n","n"],["d","d"],["b","b"],["o","aa"],["x","ks"]],
  sees: [["s","s"],["ee","iy"],["s","z"]],
  she: [["sh","sh"],["e","iy"]],
  sings: [["s","s"],["i","ih"],["ng","ng"],["s","z"]],
  slide: [["s","s"],["l","l"],["i","ay"],["d","d"],["e",null]],
  smile: [["s","s"],["m","m"],["i","ay"],["l","l"],["e",null]],
  so: [["s","s"],["o","oh"]],
  some: [["s","s"],["o","ah"],["m","m"],["e",null]],
  splash: [["s","s"],["p","p"],["l","l"],["a","ae"],["sh","sh"]],
  starts: [["s","s"],["t","t"],["ar","ar"],["ts","ts"]],
  sun: [["s","s"],["u","ah"],["n","n"]],
  sunday: [["s","s"],["u","ah"],["n","n"],["d","d"],["ay","ey"]],
  swims: [["s","s"],["w","w"],["i","ih"],["m","m"],["s","z"]],
  swing: [["s","s"],["w","w"],["i","ih"],["ng","ng"]],
  the: [["th","dh"],["e","uh"]],
  three: [["th","th"],["r","r"],["ee","iy"]],
  to: [["t","t"],["o","uw"]],
  today: [["t","t"],["o","uh"],["d","d"],["ay","ey"]],
  together: [["t","t"],["o","uh"],["g","g"],["e","eh"],["th","dh"],["er","er"]],
  tree: [["t","t"],["r","r"],["ee","iy"]],
  two: [["t","t"],["wo","uw"]],
  up: [["u","ah"],["p","p"]],
  very: [["v","v"],["e","eh"],["r","r"],["y","iy"]],
  wake: [["w","w"],["a","ey"],["k","k"],["e",null]],
  wakes: [["w","w"],["a","ey"],["k","k"],["e",null],["s","s"]],
  was: [["w","w"],["a","ah"],["s","z"]],
  we: [["w","w"],["e","iy"]],
  wheee: [["wh","w"],["eee","iy"]],
  with: [["w","w"],["i","ih"],["th","th"]],
  yellow: [["y","y"],["e","eh"],["ll","l"],["ow","oh"]],
  yum: [["y","y"],["u","ah"],["m","m"]]
};
